apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: protectapp-demo
   labels:
    helm.sh/chart: demo-0.1.0
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: protectapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  minReplicas: 5
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: protectapp-demo
  targetCPUUtilizationPercentage: 50
